voteSystrm/vote/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^index/', index, name='index'),
    url(r'^show/(?P<id>[0-9]+)', show, name='show'),
    url(r'^showAction/(?P<id>[0-9]+)', showAction, name='showAction'),
]

voteSystrm/voteSystrm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'voteSystrm.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^vote/', include('vote.urls', namespace='vote'))
]

voteSystrm/vote/models.py
# coding: utf-8
from django.db import models

class Obj(models.Model):
    objName = models.CharField(max_length=32, blank=False, verbose_name="项目名称")
    objCreateTime = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    flog = models.IntegerField(default=0) #0为单选，1为多选

    def __unicode__(self):
        return self.objName

    class Meta:
        verbose_name = "项目"
        verbose_name_plural = "项目"
        ordering = ["id"]

class Option(models.Model):
    obj = models.ForeignKey(Obj) # 创建外键
    option = models.CharField(max_length=32, blank=False, verbose_name="选项")
    polls = models.IntegerField(default=0, verbose_name="票数")
    optionCreateTime = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __unicode__(self):
        return self.option

    class Meta:
        verbose_name = "选项"
        verbose_name_plural = "选项"
        ordering = ["id"]

voteSystrm/vote/views.py
# coding: utf-8
from django.shortcuts import render
from models import Obj, Option

def index(request):
    objs = Obj.objects.all()
    context = {'objs': objs}
    return render(request, 'index.html', context)

def show(request, id):
    obj = Obj.objects.get(pk=id) # 获取主表的数据
    optionTable = obj.option_set # 获取子表的表
    optionContent = optionTable.all() # 获取子表的对象
    context = {'obj':obj, 'optionContent':optionContent}
    return render(request, 'show.html', context)

def showAction(request, id):
    obj = Obj.objects.get(pk=id)  # 获取主表的数据
    optionTable = obj.option_set  # 获取子表的表
    optionContent = optionTable.all()
    if obj.flog:
        choiceId = request.POST.getlist('myOption') #获取用户所投选项的id
        if choiceId == []:
            context = {'obj': obj, 'optionContent': optionContent,'getError': "你倒是选一个呀SB！"}
            return render(request, 'show.html', context)
        for idNum in choiceId:
            optionObj = optionTable.get(pk=idNum) # 提取用户所投选项的对象文件
            optionObj.polls += 1 # 将用户所投选项的票数增加1
            optionObj.save() # 保存该对象的更改
    else:
        try:
            choiceId = request.POST['myOption'] #获取用户所投选项的id
        except KeyError,Option.DoesNotExist:
            context = {'obj': obj, 'optionContent': optionContent,'getError': "你倒是选一个呀SB！"}
            return render(request, 'show.html', context)
        optionObj = optionTable.get(pk=choiceId) # 提取用户所投选项的对象文件
        optionObj.polls += 1 # 将用户所投选项的票数增加1
        optionObj.save() # 保存该对象的更改

    # 将保存后的数据渲染到页面
    obj = Obj.objects.get(pk=id)
    optionTable = obj.option_set
    optionContent = optionTable.all()
    context = {'obj': obj, 'optionContent': optionContent}
    return render(request, 'showResult.html', context)

voteSystrm/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票首页</title>
    <style>
        .mainBox{
            width: 200px;
            height: 300px;
            background: #f2f2f2;
            border:2px solid #000;
            border-radius: 10%;
            position: absolute;
            top:0;
            left:0;
            right:0;
            bottom:0;
            margin: auto;
        }
        .header{
            text-align: center;
        }
        .content{
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="mainBox">
        <h1 class="header">投票项目</h1>
        {% for obj in objs %}
            <div class="content">
                <a href="{% url 'vote:show' obj.id %}">{{ obj.objName }}</a>
            </div><br>
        {% endfor %}
    </div>
</body>
</html>

voteSystrm/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>choice</title>
    <style>
        .mainBox{
            width: 200px;
            height: 300px;
            background: #f2f2f2;
            border:2px solid #000;
            border-radius: 10%;
            position: absolute;
            top:0;
            left:0;
            right:0;
            bottom:0;
            margin: auto;
        }
        .header{
            text-align: center;
        }
        .opt{
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="mainBox">
        {# 这里的id是传给urls的然后urls再传给views。用途是通过id提取主表数据，再通过option_set处理子表 #}
        <form action="{% url 'vote:showAction' obj.id %}" method="post"> {# method方法记得加+++ #}
            {% csrf_token %}
            <h2 class="header">{{ obj.objName }}</h2>
            {% for option in optionContent %}
                {# 这里的id是点击提交后传递给POST方法的id #}
                {% if obj.flog %}
                    <input type="checkbox" name="myOption" value="{{ option.id }}">{{ option.option }}<br>
                {% else %}
                    <input type="radio" name="myOption" value="{{ option.id }}">{{ option.option }}<br>
                {% endif %}
            {% endfor %}
            <br>
            <div class="opt">
                <input type="submit" value="提交投票">
                <a href="{% url 'vote:index' %}">返回主页</a>
            </div>
        </form>
    <p class="opt">{{ getError }}</p>
    </div>
</body>
</html>

voteSystrm/templates/showResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果</title>
    <style>
        .mainBox{
            width: 200px;
            height: 300px;
            background: #f2f2f2;
            border:2px solid #000;
            border-radius: 10%;
            position: absolute;
            top:0;
            left:0;
            right:0;
            bottom:0;
            margin: auto;
        }
        .header{
            text-align: center;
        }
        .opt{
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="mainBox">
        <h2 class="header">{{ obj.objName }}</h2>
        <ul>
        {% for option in optionContent %}
            <li>{{ option.option }}:{{ option.polls }}票</li>
        {% endfor %}
        </ul>
        <div class="opt"><a href="{% url 'vote:index' %}">返回主页</a></div>
    </div>
</body>
</html>